server:
  port: 1010

moex:
  bonds:
    corporate:
      url: "https://iss.moex.com/iss/engines/stock/markets/bonds/boards/TQCB/securities.xml?iss.meta=off&iss.only=securities&securities.columns=SECID,PREVADMITTEDQUOTE,SHORTNAME"
    government:
      url: "https://iss.moex.com/iss/engines/stock/markets/bonds/boards/TQOB/securities.xml?iss.meta=off&iss.only=securities&securities.columns=SECID,PREVADMITTEDQUOTE,SHORTNAME"


  spring:
    cache:
      caffeine:
        spec: maximumSize=48,expireAfterAccess=1h

  logging:
    level:
      ru.dakon.CurrencyCbrService.cbrclient: INFO
    file:
      name: logs/MoexStockService.log